image: node:latest

stages:
  - validate
  - deploy

html-validate:
  stage: validate
  script:
    - npm install -g html-validate
    - html-validate "**/*.html"
  only:
    - main
    - merge_requests

# Deployment stage is commented out but can be uncommented and configured when needed
# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy to production server"
#   only:
#     - main 