image: alpine:latest

pages:
  stage: deploy
  script:
    # Create the public directory
    - mkdir -p public
    # Copy all HTML files and assets to the public directory
    - cp -r *.html public/ 2>/dev/null || true
    - cp -r css public/ 2>/dev/null || true
    - cp -r js public/ 2>/dev/null || true
    - cp -r images public/ 2>/dev/null || true
    - cp -r assets public/ 2>/dev/null || true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

