# The Docker image that will be used to build your app
image: alpine:latest
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script: 
   - cp -r *.html public/ 2>/dev/null || true
    - cp -r css public/ 2>/dev/null || true
    - cp -r js public/ 2>/dev/null || true
    - cp -r images public/ 2>/dev/null || true
    - cp -r assets public/ 2>/dev/null || true